apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Parámetros de configuración sensibles (key-value in base64 --> echo -n "real_value" | base64)
  
  # youtube
  YOUTUBE_API_KEY: QUl6YVN5Q21CZ1FYdjNTcEltVUdKTmhVNzc2bDR1ZUtQM1J0eFlv
  
  # openAI
  OPENAI_API_KEY: c2stcHJvai01SVlEYXNFck1NRzRqaE1tSDBTQXNPR1RfV0FKVWF6c0pTVzc5SmZrbnF2dXB1dm1iUXFiZTNYNU9YS2ZZYzVKQmN0N3NZRW5UcFQzQmxia0ZKT1gyZl93NEZLQUxkanNUT1Z1NlItUlNxMzhHaDh2YlpnYkdsREZqVnBrWFhZWDNjeWYzYTE0cVRaVFBaak9GMWZYV29BOTc3SUE=
  
  # mongo
  MONGO_USER: YWRtaW4=
  MONGO_PASSWORD: bFNVMW1aQzZwam1jcU4zYQ==
  
  # twitter (X) (vars related to the APP itself, same for all users)
  X_OAUTH1_API_KEY: U21jUU1lZGkzVFBPeUNqY21NajdYV3Z3NA==
  X_OAUTH1_API_SECRET: bGljdEc5aVVNbG9peWo1d1RqQmsyZWJXVFlMZm1QWHB4ZnZiQnFrU2VHNlRuN1Ftek8=
  X_OAUTH2_API_BEARER_TOKEN: QUFBQUFBQUFBQUFBQUFBQUFBQUFBTEhXM0FFQUFBQUFVJTJCemxZcFNVZ2hPcUUzck1KQWpQSlc2bzNNcyUzREg4WWg2Rkl0c3RXTjdPdmpTN2RqMmpYUjczb0p1MjMyOW9mMzFJZGpoQ3lRcDJwTTFo
  X_OAUTH2_CLIENT_ID: WmpBd01DMWhjMWhFVlhKZmMxQldRamczVFdZNk1UcGphUQ==
  X_OAUTH2_CLIENT_SECRET: Yk1UTWowTGhJZU1UTm1haWRlVnlyaVVlZnh2UkJYNW5SRE8wUEUzeUZ0a2JQd2tyT28=
  DB_ENCRIPTION_SECRET_KEY: c3BWcGpTcHN3OUpYQjlDdWhaek8yTzJ4aDREUjc0SHBPT2VCYWZHQ3Rvcz0= #used to encript user-level X credentials in DB

